export const allPlacesByMap: Record<string, string[]> = {
  bigmap: [
    'gazel',
    'dead_posylni',
    'vremyan_case',
    'room206_water',
    'vaz_feld',
    'room114',
    'room214',
    'bomj_place',
    'place_SADOVOD_03',
  ],

  woods: ['bunker2', 'ter_015_area_1', 'huntsman_001', 'pr_scout_col', 'pr_scout_base'],

  shoreline: [
    'place_peacemaker_007_1_N1',
    'place_peacemaker_010_3',
    'place_peacemaker_004_N1',
    'place_peacemaker_004_N2',
    'place_peacemaker_009_2',
    'place_peacemaker_009_3_N1',
    'place_peacemaker_005_N1',
    'place_peacemaker_005_N2',
    'place_peacemaker_010_2',
    'huntsman_026',
    'place_peacemaker_008_4_N1',
    'place_peacemaker_008_4_N2',
    'place_peacemaker_001',
    'place_SIGNAL_01_1',
    'place_SIGNAL_01_2',
    'place_meh_sanitar_room',
    'huntsman_024_1',
    'huntsman_024_2',
    'huntsman_024_3',
    'ter_023_area_1_1',
    'ter_023_area_3_1',
    'ter_023_area_2_1',
  ],

  interchange: [
    'place_SALE_03_AVOKADO',
    'place_SALE_03_KOSTIN',
    'place_SALE_03_TREND',
    'place_SALE_03_DINO',
    'place_SALE_03_TOPBRAND',
  ],

  factory: [
    'pumproom',
    'place_pacemaker_SCOUT_01',
    'place_pacemaker_SCOUT_02',
    'place_pacemaker_SCOUT_03',
    'place_pacemaker_SCOUT_04',
    'ter_017_area_1',
    'locked_office',
  ],

  lighthouse: [
    'qlight_pr1_heli1_find',
    'qlight_hunt_fr_find',
    'qlight_find_light_merchant',
    'qlight_find_crushed_heli',
    'qlight_find_scav_group1',
    'meh_48_transponder_area_check_1',
    'meh_50_visit_area_check_1',
    'qlight_extension_medic1_exploration1',
    'qlight_extension_prapor1_exploration1',
    'qlight_extension_prapor1_exploration2',
    'qlight_extension_prapor1_exploration3',
    'qlight_extension_bariga1_exploration1',
    'qlight_extension_mechanik1_exploration1',
  ],

  rezervbase: [
    'huntsman_029',
    'prapor_024_area_2',
    'prapor_024_area_1',
    'tadeush_bmp2_area_check_2',
    'tadeush_bmp2_area_check_11',
    'tadeush_bmp2_area_check_12',
    'tadeush_bmp2_area_check_13',
    'tadeush_stryker_area_check_3',
    'tadeush_stryker_area_check_4',
    'tadeush_t90_area_check_1',
    'mechanik_exit_area_1',
    'prapor_025_area_1',
    'prapor_025_area_2',
    'prapor_025_area_3',
    'prapor_025_area_4',
    'prapor_025_area_5',
    'baraholshik_arsenal_area_1',
    'baraholshik_dejurniy_area_2',
    'baraholshik_arsenal_area_3',
    'baraholshik_arsenal_area_4',
    'baraholshik_arsenal_area_5',
  ],

  laboratory: ['peace_027_area', 'quest_zone_keeper7_saferoom', 'quest_zone_keeper7_test'],

  tarkovstreets: [
    'quest_zone_keeper8_1',
    'quest_zone_keeper8_2',
    'quest_zone_find_2st_mech',
    'quest_zone_c5_mar',
    'quest_zone_c6_kpss',
    'quest_zone_c7_mel',
    'quest_zone_c8_dom1',
    'quest_zone_c8_dom2',
    'quest_zone_c8_dom2_dead',
    'quest_zone_c11_gmed',
    'quest_zone_c16_koll_1',
    'quest_zone_c16_koll_2',
    'quest_zone_c21_look',
    'quest_zone_c25_cinem',
    'quest_zone_c27_sect',
    'quest_zone_keeper99',
    'quest_zone_c29_debt',
    'quest_zone_c25_cinem2',
    'quest_produkt1',
    'quest_produkt2',
    'quest_produkt3',
    'quest_produkt4',
    'quest_zone_find_sillent',
    'quest_zone_find_2st_kpss2',
    'quest_zone_find_2st_med_invent1',
    'quest_zone_find_2st_med_invent2',
    'Bank_points_3',
    'Bank_points_4',
    'Bank_points_6',
    'Bank_points_1',
    'Bank_points_2',
    'Bank_points_8',
    'Bank_points_9',
    'Bank_points_10',
    'Bank_points_13',
    'Bank_points_11',
    'Bank_points_12',
    'Bank_points_5',
    'Bank_points_14',
    'Bank_points_15',
    'Bank_points_16',
    'Office_enter',
    'Office_quest',
    'Hookah_quest',
    'Pharma_1',
    'Pharma_2',
    'Pharma_3',
    'fond_quest',
  ],

  groundzero: [
    'Sandbox_1_MedicalArea_exploration',
    'Sandbox_2_Kord_exploration',
    'Sandbox_2_AGS_exploration',
    'Sandbox_3_Vino_exploration',
    'Sandbox_5_DeadGroup_exploration',
    'Sandbox_5_Laborant_exploration',
    'Sandbox_5_Office_exploration',
  ],
};
