export const allZonesByMap: Record<string, string[]> = {
  bigmap: [
    'gazel',
    'place_peacemaker_007_N1',
    'place_peacemaker_002_N1',
    'place_peacemaker_002_N2',
    'place_peacemaker_002_N3',
    'extraction_zone_zibbo',
    'fuel1',
    'fuel2',
    'fuel3',
    'fuel4',
    'place_skier_12_2',
    'place_skier_11_3',
    'Q019_3',
  ],

  woods: [
    'place_peacemaker_007_2_N2',
    'place_peacemaker_007_2_N2_1',
    'place_THX_15',
    'bar_fuel3_1',
    'bar_fuel3_2',
    'bar_fuel3_3',
    'place_skier_12_3',
    'place_skier_11_2',
    'huntsman_005_1',
    'huntsman_005_2',
    'meh_45_radio_area_mark_1',
    'meh_45_radio_area_mark_2',
    'meh_45_radio_area_mark_3',
    'meh_45_radio_area_mark_4',
    'q14_8_1',
    'q14_8_2',
    'q14_8_3',
    'q14_8_4',
    'q14_8_5',
  ],

  shoreline: [
    'place_peacemaker_007_2_N3',
    'place_peacemaker_008_2_N1',
    'place_peacemaker_008_2_N2',
    'place_peacemaker_003_N1',
    'place_peacemaker_003_N2',
    'place_peacemaker_003_N3',
    'place_peacemaker_005_N1',
    'place_peacemaker_005_N2',
    'place_peacemaker_010_2',
    'place_SIGNAL_03_1',
    'place_SIGNAL_03_2',
    'place_SIGNAL_03_3',
    'place_peacemaker_001',
    'ter_013_area_1',
    'ter_013_area_2',
    'ter_013_area_3',
    'skier_022_area_1',
    'skier_022_area_2',
    'skier_022_area_3',
    'prapor_022_area_1',
    'prapor_022_area_2',
    'prapor_022_area_3',
  ],

  interchange: [
    'place_WARBLOOD_04_1',
    'place_WARBLOOD_04_2',
    'place_WARBLOOD_04_3',
    'place_skier_12_1',
    'place_skier_11_1',
    'place_merch_21_1',
    'place_merch_21_2',
    'place_merch_21_3',
    'place_merch_020_1',
    'place_merch_020_2',
    'quest_zone_keeper6_kiba_hide',
    'quest_zone_keeper6_safe_hide',
    'quest_zone_keeper6_cont_hide',
  ],

  factory: ['place_SADOVOD_01_1', 'place_SADOVOD_01_2', 'case_extraction', 'ter_017_area_1'],

  lighthouse: [
    'qlight_pr1_heli1_mark',
    'qlight_mark_vech1',
    'qlight_mark_vech2',
    'qlight_mark_vech3',
    'qlight_mark_vech4',
    'qlight_fuel_blood',
    'qlight_fuel_blood_bezovoz1',
    'qlight_fuel_blood_bezovoz2',
    'qlight_fuel_blood_bezovoz3',
    'qlight16_peace_terra',
    'meh_42_radio_area_mark_1',
    'meh_42_radio_area_mark_2',
    'meh_42_radio_area_mark_3',
    'meh_42_radio_area_mark_4',
    'qlight_extension_medic1_hide1',
    'qlight_extension_mechanik1_hide1',
  ],

  rezervbase: [
    'tadeush_bmp2_area_mark_2',
    'tadeush_bmp2_area_mark_11',
    'tadeush_bmp2_area_mark_12',
    'tadeush_bmp2_area_mark_13',
    'tadeush_stryker_area_mark_3',
    'baraholshik_fuel_area_2',
    'baraholshik_fuel_area_3',
  ],

  tarkovstreets: [
    'quest_zone_place_c14_revx_1',
    'quest_zone_place_c14_revx_2',
    'quest_zone_place_c14_revx_3',
    'quest_zone_keeper10_place',
    'quest_zone_hide_sillent',
    'quest_zone_hide_sillent2',
    'quest_zone_hide_barber1',
    'quest_zone_hide_barber2',
    'quest_city_trotil2',
    'quest_city_trotil1',
  ],

  groundzero: [],

  // TODO: define on which map those should be
  any: [
    'quest_zone_place_c24_tigr1',
    'quest_zone_place_c24_tigr2',
    'tadeush_bmp2_area_mark_12',
    'place_keeper5_1',
    'place_keeper5_2',
    'quest_zone_keeper8_1_hide1',
    'quest_zone_keeper8_1_hide2',
    'quest_zone_hide_2st_mech',
    'place_flyers1',
  ],
};
